name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          # Замени HF_USERNAME и SPACE_NAME на свои
          git remote add hf https://salarion-witch:${HF_TOKEN}@huggingface.co/spaces/salarion-witch/operation-search-api

          git push hf main --force
